#!/usr/bin/env bash
set -euo pipefail

echo "🚀 Setting up CIS Benchmark remediation lab (Question 1) on a kubeadm-provisioned cluster..."
echo

# This lab intentionally introduces kubelet + etcd CIS violations so you can remediate them.
# It is designed for a single control-plane node (kubeadm, static-pod etcd).

KUBEADM_FLAGS_FILE="/var/lib/kubelet/kubeadm-flags.env"
ETCD_MANIFEST="/etc/kubernetes/manifests/etcd.yaml"

timestamp="$(date +%Y%m%d%H%M%S)"
backup_dir="/root/cis-q01-backups-${timestamp}"
mkdir -p "${backup_dir}"

echo "📦 Backing up current configs to: ${backup_dir}"
if [[ -f "${KUBEADM_FLAGS_FILE}" ]]; then
  cp -a "${KUBEADM_FLAGS_FILE}" "${backup_dir}/kubeadm-flags.env"
else
  echo "WARN: ${KUBEADM_FLAGS_FILE} not found. This lab expects kubeadm."
fi

if [[ -f "${ETCD_MANIFEST}" ]]; then
  cp -a "${ETCD_MANIFEST}" "${backup_dir}/etcd.yaml"
else
  echo "WARN: ${ETCD_MANIFEST} not found. This lab expects etcd as a static pod."
fi

echo
echo "🧩 Introducing intentional CIS violations..."

# Generate a simulated kube-bench report for the candidate to review
KUBE_BENCH_REPORT="/root/kube-bench-report-q01.txt"
cat <<'EOF' > "${KUBE_BENCH_REPORT}"
# kube-bench (SIMULATED) — CIS Kubernetes Benchmark v1.8.x
# Target: kubeadm-provisioned control-plane node
# Date: $(date -Is)
#
# NOTE: This file is intentionally generated by the lab setup to represent the findings
# a CIS scan would flag before remediation.

[INFO] 1 Control Plane Security Configuration
[INFO] 2 Etcd Node Configuration
[INFO] 3 Control Plane Configuration
[INFO] 4 Worker Node Security Configuration

[INFO] 4 Worker Node Security Configuration
[INFO] 4.2 Kubelet
[FAIL] 4.2.1 Ensure that the --anonymous-auth argument is set to false (Automated)
       * Reason: kubelet flag --anonymous-auth is true
       * Remediation: Edit kubelet args to include --anonymous-auth=false and restart kubelet

[FAIL] 4.2.2 Ensure that the --authorization-mode argument is not set to AlwaysAllow (Automated)
       * Reason: kubelet flag --authorization-mode=AlwaysAllow
       * Remediation: Set --authorization-mode to a secure option such as Webhook or Node,RBAC and restart kubelet

[FAIL] 4.2.5 Ensure that the --authentication-token-webhook argument is set to true (Automated)
       * Reason: kubelet flag --authentication-token-webhook is false
       * Remediation: Set --authentication-token-webhook=true and restart kubelet

[INFO] 2 Etcd Node Configuration
[INFO] 2.2 Etcd Node Configuration Files
[FAIL] 2.2.4 Ensure that the --client-cert-auth argument is set to true (Automated)
       * Reason: etcd flag --client-cert-auth is false
       * Remediation: Set --client-cert-auth=true in /etc/kubernetes/manifests/etcd.yaml and allow static pod to restart

== Summary ==
1 checks PASS
0 checks WARN
4 checks FAIL
EOF

echo "📝 Generated simulated kube-bench report: ${KUBE_BENCH_REPORT}"

# 1) Kubelet violations:
# - anonymous-auth should be false (we set to true)
# - authorization-mode should not be AlwaysAllow (we set to AlwaysAllow)
# - Use webhook authn/authz where possible (we disable token webhook and avoid webhook authz)
if [[ -f "${KUBEADM_FLAGS_FILE}" ]]; then
  # Extract the quoted args, strip quotes, then manipulate
  line="$(grep -E '^KUBELET_KUBEADM_ARGS=' "${KUBEADM_FLAGS_FILE}" || true)"
  if [[ -z "${line}" ]]; then
    echo 'KUBELET_KUBEADM_ARGS=""' >> "${KUBEADM_FLAGS_FILE}"
    line='KUBELET_KUBEADM_ARGS=""'
  fi

  # Remove flags we will control, then append "bad" ones
  current_args="$(echo "${line}" | sed -E 's/^KUBELET_KUBEADM_ARGS="(.*)"/\1/')"
  # Drop existing variants
  current_args="$(echo "${current_args}" | sed -E \
    -e 's/--anonymous-auth(=|\s+)[^ ]+//g' \
    -e 's/--authorization-mode(=|\s+)[^ ]+//g' \
    -e 's/--authentication-token-webhook(=|\s+)[^ ]+//g' \
    -e 's/--authorization-webhook-cache-authorized-ttl(=|\s+)[^ ]+//g' \
    -e 's/--authorization-webhook-cache-unauthorized-ttl(=|\s+)[^ ]+//g' \
  )"
  # Normalize whitespace
  current_args="$(echo "${current_args}" | tr -s ' ' | sed -E 's/^ +| +$//g')"

  bad_flags="--anonymous-auth=true --authorization-mode=AlwaysAllow --authentication-token-webhook=false"
  new_args="${current_args} ${bad_flags}"
  new_args="$(echo "${new_args}" | tr -s ' ' | sed -E 's/^ +| +$//g')"

  # Write back
  sed -i -E "s|^KUBELET_KUBEADM_ARGS=\".*\"|KUBELET_KUBEADM_ARGS=\"${new_args}\"|g" "${KUBEADM_FLAGS_FILE}"
  echo "✅ Injected kubelet CIS violations into ${KUBEADM_FLAGS_FILE}"
fi

# 2) etcd violation:
# - Ensure --client-cert-auth=true (we set it to false or remove true)
if [[ -f "${ETCD_MANIFEST}" ]]; then
  if grep -q -- '--client-cert-auth' "${ETCD_MANIFEST}"; then
    # Force it to false
    sed -i -E 's/--client-cert-auth(=|\s+)true/--client-cert-auth=false/g' "${ETCD_MANIFEST}"
    sed -i -E 's/--client-cert-auth(=|\s+)1/--client-cert-auth=false/g' "${ETCD_MANIFEST}"
  else
    # Insert a bad flag near other etcd flags
    # Insert after first occurrence of "- --" in the command args list for readability
    awk '
      BEGIN{done=0}
      {print}
      (!done && $0 ~ /^ *- --/){
        print "    - --client-cert-auth=false"
        done=1
      }
    ' "${ETCD_MANIFEST}" > "${ETCD_MANIFEST}.tmp" && mv "${ETCD_MANIFEST}.tmp" "${ETCD_MANIFEST}"
  fi
  echo "✅ Injected etcd CIS violation into ${ETCD_MANIFEST}"
fi

echo
echo "🔁 Restarting kubelet to apply the misconfigurations (etcd static pod will be reloaded automatically)..."
systemctl daemon-reload >/dev/null 2>&1 || true
systemctl restart kubelet

echo
echo "✅ Lab setup complete."
echo
echo "Next:"
echo "1) Remediate kubelet flags to satisfy:"
echo "   - --anonymous-auth=false"
echo "   - --authorization-mode is NOT AlwaysAllow (prefer Webhook, and/or Node,RBAC)"
echo "   - Use webhook authentication/authorization where possible (e.g., --authentication-token-webhook=true, --authorization-mode=Webhook)"
echo "2) Remediate etcd to satisfy:"
echo "   - --client-cert-auth=true"
echo
echo "Hints:"
echo "- kubelet flags: ${KUBEADM_FLAGS_FILE}"
echo "- etcd static pod manifest: ${ETCD_MANIFEST}"
echo "- After fixes: systemctl restart kubelet (and validate by inspecting running components)"
