#!/usr/bin/env bash
set -euo pipefail

echo "🚀 Setting up CIS Benchmark remediation lab (Q01 v2) — CONTROLPLANE"
echo

# This version mimics the real exam more closely by placing kubelet settings in:
#   /var/lib/kubelet/config.yaml
# rather than only kubeadm-flags.env (which may not control these values in newer kubeadm setups).

KUBELET_CONFIG="/var/lib/kubelet/config.yaml"
KUBEADM_FLAGS_FILE="/var/lib/kubelet/kubeadm-flags.env"
ETCD_MANIFEST="/etc/kubernetes/manifests/etcd.yaml"
REPORT="/root/kube-bench-report-q01.txt"

ts="$(date +%Y%m%d%H%M%S)"
backup_dir="/root/cis-q01v2-backups-${ts}"
mkdir -p "${backup_dir}"

echo "📦 Backing up configs to: ${backup_dir}"
for f in "${KUBELET_CONFIG}" "${KUBEADM_FLAGS_FILE}" "${ETCD_MANIFEST}"; do
  if [[ -f "$f" ]]; then
    cp -a "$f" "${backup_dir}/$(basename "$f")"
  else
    echo "WARN: $f not found"
  fi
done

echo
echo "📝 Generating simulated kube-bench report at: ${REPORT}"
cat <<'EOF' > "${REPORT}"
# kube-bench (SIMULATED) — CIS Kubernetes Benchmark v1.8.x
# Target: kubeadm-provisioned cluster
# NOTE: This report is intentionally generated by the lab setup to represent pre-remediation findings.

[INFO] 4 Worker Node Security Configuration
[INFO] 4.2 Kubelet
[FAIL] 4.2.1 Ensure that the --anonymous-auth argument is set to false (Automated)
       * Reason: kubelet anonymous auth enabled
       * Remediation: Set authentication.anonymous.enabled=false in /var/lib/kubelet/config.yaml and restart kubelet

[FAIL] 4.2.2 Ensure that the --authorization-mode argument is not set to AlwaysAllow (Automated)
       * Reason: kubelet authorization mode AlwaysAllow
       * Remediation: Set authorization.mode to Webhook (preferred) or Node,RBAC and restart kubelet

[FAIL] 4.2.5 Ensure that the --authentication-token-webhook argument is set to true (Automated)
       * Reason: kubelet webhook authn disabled
       * Remediation: Set authentication.webhook.enabled=true and restart kubelet

[INFO] 2 Etcd Node Configuration
[FAIL] 2.2.4 Ensure that the --client-cert-auth argument is set to true (Automated)
       * Reason: etcd flag --client-cert-auth is false
       * Remediation: Set --client-cert-auth=true in /etc/kubernetes/manifests/etcd.yaml and allow static pod to restart

== Summary ==
4 checks FAIL
EOF

echo
echo "🧩 Introducing intentional CIS violations..."

# --- kubelet config.yaml (preferred exam-realistic location) ---
if [[ -f "${KUBELET_CONFIG}" ]]; then
  # Use perl to rewrite relevant YAML sections robustly
  # 1) authentication.anonymous.enabled: true
  # 2) authentication.webhook.enabled: false
  # 3) authorization.mode: AlwaysAllow
  perl -0777 -i -pe '
    # Ensure authentication block exists
    if ($_ !~ /^authentication:\n/m) {
      $_ .= "\nauthentication:\n  anonymous:\n    enabled: true\n  webhook:\n    enabled: false\n";
    }

    # anonymous.enabled
    if ($_ =~ /^authentication:\n(?:.*\n)*?  anonymous:\n(?:.*\n)*?    enabled:\s*(true|false)\s*$/m) {
      s/^(\s*anonymous:\n(?:.*\n)*?\s*enabled:\s*)(true|false)\s*$/${1}true/m;
    } else {
      # Insert anonymous block under authentication
      s/^(authentication:\n)/$1  anonymous:\n    enabled: true\n/m;
    }

    # webhook.enabled
    if ($_ =~ /^authentication:\n(?:.*\n)*?  webhook:\n(?:.*\n)*?    enabled:\s*(true|false)\s*$/m) {
      s/^(\s*webhook:\n(?:.*\n)*?\s*enabled:\s*)(true|false)\s*$/${1}false/m;
    } else {
      s/^(authentication:\n)/$1  webhook:\n    enabled: false\n/m;
    }

    # Ensure authorization block exists
    if ($_ !~ /^authorization:\n/m) {
      $_ .= "\nauthorization:\n  mode: AlwaysAllow\n";
    }

    # authorization.mode
    if ($_ =~ /^authorization:\n(?:.*\n)*?  mode:\s*\S+\s*$/m) {
      s/^(\s*mode:\s*)\S+\s*$/${1}AlwaysAllow/m;
    } else {
      s/^(authorization:\n)/$1  mode: AlwaysAllow\n/m;
    }
  ' "${KUBELET_CONFIG}"

  echo "✅ Injected kubelet CIS violations into ${KUBELET_CONFIG}"
else
  echo "WARN: ${KUBELET_CONFIG} not found. This lab expects kubeadm-managed kubelet config."
fi

# --- etcd manifest ---
if [[ -f "${ETCD_MANIFEST}" ]]; then
  if grep -q -- '--client-cert-auth' "${ETCD_MANIFEST}"; then
    sed -i -E 's/--client-cert-auth(=|\s+)(true|1)/--client-cert-auth=false/g' "${ETCD_MANIFEST}"
    sed -i -E 's/--client-cert-auth(=|\s+)(false|0)/--client-cert-auth=false/g' "${ETCD_MANIFEST}"
  else
    awk '
      BEGIN{done=0}
      {print}
      (!done && $0 ~ /^ *- --/){
        print "    - --client-cert-auth=false"
        done=1
      }
    ' "${ETCD_MANIFEST}" > "${ETCD_MANIFEST}.tmp" && mv "${ETCD_MANIFEST}.tmp" "${ETCD_MANIFEST}"
  fi
  echo "✅ Injected etcd CIS violation into ${ETCD_MANIFEST}"
else
  echo "WARN: ${ETCD_MANIFEST} not found. This lab expects etcd as a static pod on the controlplane."
fi

echo
echo "🔁 Restarting kubelet to apply misconfigurations..."
systemctl daemon-reload >/dev/null 2>&1 || true
systemctl restart kubelet

echo
echo "✅ CONTROLPLANE lab setup complete."
echo
echo "Candidate should now remediate using the kube-bench report:"
echo "  sudo cat ${REPORT}"
echo
echo "If you also have a worker node (node01), run the companion setup script on that node:"
echo "  Q01v2_LabSetUp_node.bash"
